/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksBakaybankRouteImport } from './routes/api/public/webhooks/bakaybank'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBakaybankRoute =
  ApiPublicWebhooksBakaybankRouteImport.update({
    id: '/api/public/webhooks/bakaybank',
    path: '/api/public/webhooks/bakaybank',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/webhooks/bakaybank': typeof ApiPublicWebhooksBakaybankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/webhooks/bakaybank': typeof ApiPublicWebhooksBakaybankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/webhooks/bakaybank': typeof ApiPublicWebhooksBakaybankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/webhooks/bakaybank'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/webhooks/bakaybank'
  id: '__root__' | '/' | '/api/public/webhooks/bakaybank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicWebhooksBakaybankRoute: typeof ApiPublicWebhooksBakaybankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/bakaybank': {
      id: '/api/public/webhooks/bakaybank'
      path: '/api/public/webhooks/bakaybank'
      fullPath: '/api/public/webhooks/bakaybank'
      preLoaderRoute: typeof ApiPublicWebhooksBakaybankRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicWebhooksBakaybankRoute: ApiPublicWebhooksBakaybankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
